# Generated by Django 4.0.2 on 2022-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_password', models.CharField(max_length=10)),
                ('owner_contact', models.CharField(max_length=12)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_address', models.TextField()),
                ('owner_dob', models.DateField()),
                ('owner_age', models.IntegerField(max_length=3)),
            ],
            options={
                'db_table': 'owner',
            },
        ),
    ]
