# Generated by Django 4.0.2 on 2022-03-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_password', models.CharField(max_length=20)),
                ('owner_contact', models.CharField(max_length=12, null=True)),
                ('owner_email', models.EmailField(max_length=30, null=True)),
                ('owner_address', models.TextField(max_length=50, null=True)),
                ('owner_dob', models.DateField(null=True)),
                ('owner_age', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'owner',
            },
        ),
    ]
