# Generated by Django 4.0.2 on 2022-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudfunc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_age',
            field=models.IntegerField(),
        ),
    ]
