# Generated by Django 4.0.2 on 2022-02-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudfunc', '0002_alter_owner_owner_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_name',
            field=models.CharField(max_length=20),
        ),
    ]
