# Generated by Django 4.0.2 on 2022-02-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudfunc', '0004_remove_owner_owner_address_remove_owner_owner_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_address',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_contact',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_password',
            field=models.CharField(max_length=20),
        ),
    ]
