# Generated by Django 4.0.2 on 2022-03-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=20)),
                ('user_contact', models.IntegerField()),
                ('user_age', models.IntegerField()),
                ('user_address', models.TextField()),
                ('user_dob', models.DateField()),
            ],
            options={
                'db_table': 'userhome',
            },
        ),
    ]
