# Generated by Django 4.0.2 on 2022-02-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhome',
            name='user_password',
            field=models.CharField(max_length=20),
        ),
    ]
