# Generated by Django 4.0.2 on 2022-02-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_userhome_user_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userhome',
            table='userhome',
        ),
    ]
