# Generated by Django 4.0.2 on 2022-02-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_order_garage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_garage',
        ),
    ]
