# Generated by Django 4.0.2 on 2022-02-28 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_order_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_garage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='order.park'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='order',
            table='order_pay',
        ),
    ]
